import mirrorCreator from 'mirror-creator';

export default mirrorCreator([
    'UPDATE_URL',
    'UPDATE_PODCAST_FILTER_TERM',
    'FETCH_FEED',
    'FETCH_FEED_PENDING',
    'FETCH_FEED_SUCCESS',
    'FETCH_FEED_FAILURE',
    'PLAY_EPISODE_PENDING',
    'PLAY_EPISODE_SUCCESS',
    'PLAY_EPISODE_FAILURE',
    'QUEUE_EPISODE_PENDING',
    'QUEUE_EPISODE_SUCCESS',
    'QUEUE_EPISODE_FAILURE',
    'TOGGLE_EPISODE_EXPANDED',
    'SHOW_PODCAST_LIST',
    'TOGGLE_FEED_CACHING_PENDING',
    'TOGGLE_FEED_CACHING_SUCCESS'
]);
